### ISSUE TITLE
Ttest query

### ISSUE THREAD

**Issue by nsankar** [jmkuebler/auto-tst#8]
Hi,
Thanks for developing this interesting package. How is auto-tst different from Scipy 2 sample T-test?  apart from its built in integration with AutoGluon.

Also can we use scikitlearn  models in the scope of model=YourCustomModel ?

**Comment by jmkuebler** [comment]
Thanks @nsankar for your question:
a) auto-tst vs. [scipy 2 sample t-test](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html):
`autotst` learns a data representation in the first stage, and test on held-out data in the second stage. The second stage is indeed closely related to the t-test. Using the scipy test in the second stage should be quite similar. One should use it though with permutations (because we cannot assume normality) and do a one-sided test (we train such that the first sample should have larger mean). Another difference is that scipy t-test uses a normalized test statistic, while we simply use the difference in means. The crucial point of our test is though, that we automatically learn a representation in the first stage that maximizes the asymptotic test power, see our paper.

b) Yes, you can totally also wrap scikitlearn models. If you do so, feel free to open pull request, or if you struggle feel free to ping me.
